### ISSUE TITLE
pypy irc log lines with "a->b"  show only "b"

### ISSUE THREAD

**Issue by mattip** [quodlibet/quodlibet-continuous#1]
Any irc chat lines that contain ``->`` apparently are cut off and show only the content after the ``->``. This would appear to be form not properly escaping the content, which might be a security risk as well.

I looked around a bit but could not find the logging code, if you give me a hint maybe I can suggest a patch

Thanks so much for hosting this, it is my preferable way to read IRC logs!

**Comment by lazka** [comment]
huh, someone is using this? :D

**Comment by mattip** [comment]
:) You can see the issue in this line 
http://quodlibet.duckdns.org/irc/pypy/latest.log.html#t19:19:43 
compared to this line 
https://botbot.me/freenode/pypy/msg/77622373/

**Comment by lazka** [comment]
Filed upstream: https://github.com/mgedmin/irclog2html/issues/19

**Comment by lazka** [comment]
A workaround would be possible.. but that not sure if it's worth the trouble.

**Comment by lazka** [comment]
Fixed: https://quodlibet.duckdns.org/irc/pypy/pypy_2016-12-07.log.html#t19:19:43
